- name: a10_cgnv6_one_to_one_pool Example Playbook
  hosts: localhost
  connection: local
  tasks:
  - name: a10_cgnv6_one_to_one_pool
    a10_cgnv6_one_to_one_pool:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      state: "present"
      get_type: "single"
      start_address: "10.10.7.15"
      vrid: 1
      netmask: "255.0.0.0"
      end_address: "10.10.8.16"
      shared: "false"
      pool_name: "MyPool"
