- name: a10_cgnv6_logging Playbook
  hosts: localhost
  connection: local
  tasks:
  - name: a10_cgnv6_logging
    a10_cgnv6_logging:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      state: "present"
      nat_quota_exceeded:
        level: "warning"
      sampling_enable:
      - counters1: "all"
      nat_resource_exhausted:
        level: "warning"
