- name: a10_cgnv6_scaleout_nat_ip_hashing_scheme Example Playbook
  hosts: localhost
  connection: local
  tasks: 
  - name: a10_cgnv6_scaleout_nat_ip_hashing_scheme 
    a10_cgnv6_scaleout_nat_ip_hashing_scheme: 
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      hashing_type: "route-aggregation"
