- name: a10_cgnv6_service_group_member Playbook
  hosts: localhost
  connection: local
  tasks:
  - name: a10_cgnv6_service_group_member
    a10_cgnv6_service_group_member: 
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      state: "present"
      partition: "shared"
      get_type: "single"
      port: 8080
      sampling_enable:
      - counters1: "all"
      user_tag: "usr1" 
      name: "s1"
      service_group_name: "MyName"
